"""user update

Revision ID: 19c3a6b4f697
Revises: 31a64fecd30d
Create Date: 2022-10-25 12:15:28.327971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19c3a6b4f697'
down_revision = '31a64fecd30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstName', sa.String(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=64), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstName')
    # ### end Alembic commands ###
