"""create tables

Revision ID: 55886ad13e93
Revises: 4f4d05931609
Create Date: 2023-01-05 21:21:08.000848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55886ad13e93'
down_revision = '4f4d05931609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(' qoute', sa.Column('panels_parallel', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(' qoute', 'panels_parallel')
    # ### end Alembic commands ###
