"""added date to tables

Revision ID: ac4b5d121b9d
Revises: 34fd5a08c29d
Create Date: 2022-09-27 10:54:48.138632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac4b5d121b9d'
down_revision = '34fd5a08c29d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('comment', sa.String(length=250), nullable=False),
    sa.Column('comment_owner', sa.String(length=50), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_owner')
    )
    op.add_column('product', sa.Column('update_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'update_at')
    op.drop_table('comments')
    # ### end Alembic commands ###
