"""migartions 

Revision ID: b0e3df6d6770
Revises: 34027ad17373
Create Date: 2022-11-24 10:49:08.619969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0e3df6d6770'
down_revision = '34027ad17373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(' qoute', sa.Column('name_panal', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(' qoute', 'name_panal')
    # ### end Alembic commands ###
