"""added date to tables

Revision ID: cff30eb96ea6
Revises: ae3ada087bfc
Create Date: 2022-09-28 23:16:28.968980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cff30eb96ea6'
down_revision = 'ae3ada087bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_format',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.String(length=50), nullable=True),
    sa.Column('closed_all_day', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_format')
    # ### end Alembic commands ###
